### ISSUE TITLE
Need more information when a connection fails

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/esajpip-SWHV#12]
In our logs on our JPIP server we are seeing several errors accepting connections.
We are well under the "max connections" configuration setting, so the connection should not be blocked.
For more info, when a socket connection fails, it should log errno so we can see the supposed cause of the failure.

2022-02-11 19:01:12,232: /home/ireland/esajpip_0.7/esajpip-SWHV/esajpip/esajpip/src/esa_jpip_server.cc:130: ERROR: Problems accepting a new connection

**Comment by bogdanni** [comment]
Could you please try with the latest commit ([4b1bbe6](https://github.com/Helioviewer-Project/esajpip-SWHV/commit/4b1bbe63df8c38c76bd8877e1e816a6956998126))?
