### ISSUE TITLE
The function gethostbyaddr returns NULL and HOST_NOT_FOUND error

### ISSUE THREAD

**Issue by josejuansanchez** [Helioviewer-Project/esajpip-SWHV#8]
I am running the server on **Ubuntu 16.04.2 LTS (kernel 4.4.0-83-generic)** and the server doesn't listen at the port specified in the config file. Every time I start the server, it uses a random port. I think this behaviour is due a minor issue with the function `gethostbyaddr`.

**Comment by bogdanni** [comment]
Thanks, I'll check this once I have enough bandwidth.

**Comment by bogdanni** [comment]
Cannot reproduce. I added build instructions to the README, maybe those solve the issue for you.
Most of the code in that area should probably be replaced.
